service: rd-cost-notification
frameworkVersion: ">=1.0.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  memorySize: 128
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ce:GetCostAndUsage
      Resource: "*"
    - Effect: Allow
      Action:
        - sts:GetCallerIdentity
      Resource: "*"
plugins:
  - serverless-webpack
functions:
  costNotify:
    handler: index.cost
    events:
      - schedule: cron(0 1 2 * ? *)
    environment:
      HOOKS_URL: ${env:HOOKS_URL}
      CHANNEL: ${env:CHANNEL}
      TZ: Asia/Tokyo
